services:
  - type: web
    name: ml-ddos-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=$PORT --server.headless=true
    autoDeploy: false
    envVars:
      - key: BACKEND_API_URL
        sync: false
